language: node_js
node_js: "5"
sudo: false
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: WeQnQv2sSRjaMD9Ml3j7EyYkTg6JJ2pxYM+eCWRavtUk0mb09hgS3bGiqDQzDScav+63beVWz8725XNrx3nmWBQQeh4IySSe24f/QMz2q8PdjnL7W6OWViVEjR4sC0xq7YiYLk5HK+a6hG/5PyRUcPPjtXgqtCUh21kTbNP7TlLAeL8gAilQU9rS31QoQ88S9e0trD0RdoC4uj0Cn29BnEK4AhkAkjcfb3Q6O3aQtO2GYbaZaSk60vl1rn3uBxC3L2dDq7xGmXnk50jBfP0j4H/TQBWmSlFo4zK0ibqWw7UASX5BHAfaLQCmF2kHJgI/hJNfVJFc14+S7FY4XOkEVvak2thP/uNKxzoLc/jfRijEsWi3BBmDX3KzXp0cHaf0h1e/ZX5pU9gc/0N2BKIBe11ikA8Bgz+h9iDsD0C+IQDef4zzTIWq9XvSBojF4+BT/Ge2HrxRsZ0nSuTFLF8FYttIwHeDhiWVepjJkXZbH5n0XtSgiRhdjSD77bXpi9IZLXkYNnjMKKjvf2hP+4hAy3k/B8hRVa9wGiTC5oOgPEc8XhwsveBKxud0tL0hCUaarRLPwynd7PlQpni/gNchAYG9jvs+3Nv6OpRXfddKw/Dx6oNU5MjrJm+WFXLC5Hrx3CBDCEYR5NDAKGT72jcD89J0MPmAzEiB8fwk2i8I81k=
  on:
    tags: true
    all_branches: true
