language: node_js
node_js:
- '0.12'
sudo: false
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: ihM/pVc6oiAuyd+xOwM/SZLLJVtuCf8InB3SphMo3iPCvoiTqulVpHWP7QJ3A6vGFxCPf0M+MG31DbnB3gOaNbszL/sAhBPP22kEtr4jHnN9Z80lvRDTJFqTkAtkSVgUwghhd55k/WfAf3iAVxddvAb4eXf+00Ik9tZ3H3jR3IkGUAVwTTVNDjRU2Bd6B/fpLK6/EbAbMA67btVyI1id3uD4TvXMKgj2SsS08MeWmgZteAiVTKrMUdABxo9192aQjN2IiEZVI60ygjD+rkicfAQfisS7YwdG7R51uIGijHdVfAT1yct85GY3lB5oIMUDcUvAjnLJD9KTabBirrL1VGCbjsAUWpdUcUoV606bQVPy+ENK4SDItU5GdR7gqqbc5dOJd4G/ypc14EV+W8BQBMO2syTBs5N12ic7mClIP+ZDBgummDBHT2KjMaOF7hBOBDliCVHdugzHL8WARRJYLPPH9EY4rMoY56fqThcee9wH6AYevvgiZRZ+k2yovI6s8vPiomwpq0Ph9RMn6FloNtxHya60dPm28MZxWDlQebx4hamYVWvRvCs5te2xcnBP7+AmFCE7Ssb9dKNfy4bmuIj78fuuAbcm+CIVk5l6dwLbbNA5hL4E1A8goq+lfMxKSnhHiXWqaIWR5pnlyXHdJYfvKMG8K6PWE98YZd/hvZg=
  on:
    tags: true
    all_branches: true
